parameters: {}
environment: {}
packages:
    - name: eagle0
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: names
          binary: false
          main: "Names"
          runtime: go:1.20
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
