name: Name Generator Deploy

on:
  push:
    branches: [ "main" ]
    paths: "packages" 
  pull_request:
    paths: "packages" 

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Run tests
        run: |
          cd packages/eagle0/names
          go test github.com/nolen777/name-generator/packages/eagle0/names/...
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy
        if: success()
        run: |
          # Deploy the name generator
          cd ../../..
          doctl serverless install
          doctl serverless connect eagle0
          doctl serverless deploy name-generator
