name: Name Generator Deploy

on:
  pull_request:
    types: [opened, reopened, edited]

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Setup Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Run tests
        run: |
          cd packages/eagle0/names
          go test github.com/nolen777/name-generator/packages/eagle0/names/...
